apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-distributor
  annotations:
    xlscsde.nhs.uk/flux-branch: ${secrets_distributor_branch}
spec:
  targetNamespace: ${secrets_distributor_namespace}
  releaseName: secrets-distributor
  chart:
    spec:
      chart: secrets-distributor
      version: ${secrets_distributor_chart_version}
      sourceRef:
        kind: HelmRepository
        name: secrets-distributor
        namespace: ${secrets_distributor_namespace}
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  - kind: ConfigMap
    name: secret-distributor-config