apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${secrets_distributor_namespace}
resources:
- secrets-distribution.yaml
configMapGenerator:
  - name: secret-mount
    files:
      - TESTING=TESTING
generatorOptions:
  disableNameSuffixHash: true